server:
  port: 10086


#文档转换路径配置
doc:
  convert:
    docpath: D:/doc/
    imgspath: D:/image/
aliyun:
  oss:
    accessKeyId:
    accessKeySecret:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket: suyublog


